spring.application.name=person-crud

spring.datasource.url=jdbc:mysql://localhost:3306/bd_aliaga
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true